tap "beeftornado/rmtree"
tap "bramstein/webfonttools"
tap "eddieantonio/eddieantonio"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
brew "ack"
brew "gettext"
brew "sqlite"
brew "xz"
brew "pixman"
brew "cairo"
brew "fribidi"
brew "gobject-introspection"
brew "libffi"
brew "antigen"
brew "little-cms2"
brew "aria2"
brew "autoconf"
brew "automake"
brew "bash"
brew "bash-completion@2"
brew "bat"
brew "binutils"
brew "gmp"
brew "isl"
brew "mpfr"
brew "p7zip"
brew "ssdeep"
brew "binwalk"
brew "boost"
brew "brew-cask-completion"
brew "coreutils"
brew "libevent"
brew "popt"
brew "s-lang"
brew "newt"
brew "tmux"
brew "byobu"
brew "ccat"
brew "lame"
brew "libass"
brew "x264"
brew "xvid"
brew "ffmpeg"
brew "chromaprint"
brew "cifer"
brew "cloc"
brew "cmake"
brew "cowsay"
brew "dark-mode"
brew "openjdk"
brew "dex2jar"
brew "diff-so-fancy"
brew "dns2tcp"
brew "docker", link: false
brew "docker-compose", link: false
brew "dos2unix"
brew "doxygen"
brew "exa"
brew "fcrackzip"
brew "findutils"
brew "flatbuffers"
brew "foremost"
brew "fortune"
brew "fzf"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "libxml2"
brew "gnumeric"
brew "libgpg-error"
brew "libassuan"
brew "libgcrypt"
brew "libksba"
brew "libusb"
brew "pinentry"
brew "gnupg"
brew "grep"
brew "libtool"
brew "hashpump"
brew "httpie"
brew "hydra"
brew "jasper"
brew "imagemagick"
brew "jenv"
brew "john"
brew "keychain"
brew "knock"
brew "libdnet"
brew "libusb-compat"
brew "lolcat"
brew "lynx"
brew "m-cli"
brew "mackup"
brew "mas"
brew "maven"
brew "micro"
brew "moreutils"
brew "mpv"
brew "narwhal"
brew "netpbm"
brew "nmap"
brew "node"
brew "ntfs-3g"
brew "openssh"
brew "pandoc"
brew "pigz"
brew "pngcheck"
brew "pth"
brew "pv"
brew "pyenv"
brew "rename"
brew "rhino"
brew "ringojs"
brew "ripgrep"
brew "sbt"
brew "scala"
brew "screen"
brew "snzip"
brew "socat"
brew "speedtest-cli"
brew "sqlmap"
brew "ssh-copy-id"
brew "sshfs"
brew "subversion", link: false
brew "tcpflow"
brew "tcpreplay"
brew "tcptrace"
brew "testssl"
brew "thefuck"
brew "tig"
brew "tldr"
brew "tree"
brew "unixodbc"
brew "vbindiff"
brew "vim"
brew "watch"
brew "webkit2png"
brew "wget"
brew "yarn"
brew "you-get"
brew "zopfli"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "bramstein/webfonttools/sfnt2woff"
brew "bramstein/webfonttools/sfnt2woff-zopfli"
brew "bramstein/webfonttools/woff2"
brew "eddieantonio/eddieantonio/imgcat", link: false
mas "Amphetamine", id: 937984704
mas "Anesidora", id: 1369500258
mas "Binaural", id: 946812450
mas "Bitwarden", id: 1352778147
mas "Black Out", id: 1319884285
mas "com.apptorium.Workspaces", id: 1219826448
mas "Core Tunnel", id: 1354318707
mas "Deliveries", id: 924726344
mas "Display Menu", id: 549083868
mas "Download Shuttle", id: 847809913
mas "EasyFind", id: 411673888
mas "Evernote", id: 406056744
mas "exifpurge", id: 784466108
mas "Expressions", id: 913158085
mas "GarageBand", id: 682658836
mas "GIF Brewery 3", id: 1081413713
mas "GIPHY CAPTURE", id: 668208984
mas "Glance", id: 1513574319
mas "Helium", id: 1054607607
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PCalc", id: 403504866
mas "Pixelmator Pro", id: 1289583905
mas "PopClip", id: 445189367
mas "Reeder", id: 880001334
mas "RetroClip", id: 1332064978
mas "Serenity", id: 1185371817
mas "Shotty", id: 1250306151
mas "Telegram", id: 747648890
mas "Todoist", id: 585829637
mas "Unsplash Wallpapers", id: 1284863847
mas "WhatsApp", id: 1147396723
mas "Xcode", id: 497799835
mas "Zonerly", id: 1304170322
vscode "eriklynd.json-tools"
vscode "james-yu.latex-workshop"
vscode "ms-azuretools.vscode-docker"
vscode "ms-vscode-remote.remote-containers"
vscode "redhat.java"
vscode "tecosaur.latex-utilities"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vscjava.vscode-gradle"
vscode "vscjava.vscode-java-debug"
vscode "vscjava.vscode-java-dependency"
vscode "vscjava.vscode-java-pack"
vscode "vscjava.vscode-java-test"
vscode "vscjava.vscode-maven"
vscode "znck.grammarly"
